# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo $AWS_ACCESS_KEY_ID
      - run: npm install -q
      - run: node_modules/.bin/ng build --prod
      - run: node deploy.js
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/circleci-docs
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync dist/ac-sats s3://ac-stats --delete


